const I18N = {
  en: {
    langLabel: 'Switch to Chinese', langButton: '中', gathering: 'Gathering', round: (n) => `Round ${n} / 5`, waitingPlayers: 'Waiting for players',
    hiddenEmpty: 'Your hidden role hand will appear here.', hiddenSelection: (n) => `Your hidden selection · ${n}/4`, hiddenLocked: (n) => `Hidden hand locked · ${n}/4 resolved`,
    chooseFour: 'Choose exactly four', ready: 'Ready', readyDone: 'Ready ✓', lock: (n) => `Lock ${n}/4`, locked: 'Locked ✓', takeFavor: 'Take Favor', makeClaim: 'Make Claim', challengeClaim: 'Challenge Claim',
    rematch: 'Rematch', waitingCircle: 'Waiting for the circle…', shareWin: '✦ You share the highest circle ✦', covenComplete: 'The coven is complete',
    finalClaim: (name) => `Final claim: ${name || 'none'}`, circleWaits: 'The circle waits', chooseSecret: 'Choose roles in secret',
    seer: (roles, count) => `Seer saw ${roles || 'nothing'} (${count} remaining)`, vp: 'VP', player: 'player',
    roles: {
      herbalist: ['🌿','Herbalist','Herb'], miner: ['💎','Miner','Crystal'], channeler: ['🔮','Channeler','Mana'], merchant: ['🪙','Merchant','Coin'],
      alchemist: ['⚗️','Alchemist','Potions'], seer: ['👁️','Seer','Peek'], ritualist: ['🕯️','Ritualist','Rituals'], thief: ['🗝️','Thief','Steal']
    },
    rituals: {'verdant-moon':'Verdant Moon','glass-star':'Glass Star','root-crown':'Root Crown','triple-flame':'Triple Flame','silver-well':'Silver Well','thorn-prism':'Thorn Prism'},
    rules: `<h2>How to Play</h2><p>Each round, secretly choose four of the eight roles. The lead player starts one of their remaining roles and chooses <b>Favor</b> for a safe immediate effect or <b>Claim</b> for the stronger action.</p><p>Going clockwise, every player who also chose that role must respond. A later Claim steals the main action. When the circle ends, only the final claimant gets the Claim effect.</p><p>After five rounds, score potion and ritual VP plus 1 VP per 3 coins. Ties go to the player with more herb + mana + crystal, then remain shared.</p><h3>Roles</h3><ul><li>🌿 Herbalist — herbs</li><li>💎 Miner — crystals</li><li>🔮 Channeler — mana</li><li>🪙 Merchant — coins</li><li>⚗️ Alchemist — potions</li><li>👁️ Seer — private role information</li><li>🕯️ Ritualist — public ritual progress</li><li>🗝️ Thief — coins</li></ul>`
  },
  zh: {
    langLabel: '切换到英文', langButton: 'EN', gathering: '集结中', round: (n) => `第 ${n} / 5 轮`, waitingPlayers: '等待玩家加入',
    hiddenEmpty: '你的秘密角色手牌会显示在这里。', hiddenSelection: (n) => `你的秘密选择 · ${n}/4`, hiddenLocked: (n) => `秘密手牌已锁定 · 已结算 ${n}/4`,
    chooseFour: '必须正好选择四个角色', ready: '准备', readyDone: '已准备 ✓', lock: (n) => `锁定 ${n}/4`, locked: '已锁定 ✓', takeFavor: '选择恩惠', makeClaim: '发起主张', challengeClaim: '争夺主张',
    rematch: '再来一局', waitingCircle: '等待秘社行动…', shareWin: '✦ 你并列秘社最高荣誉 ✦', covenComplete: '秘社仪式已完成',
    finalClaim: (name) => `最终主张者：${name || '无'}`, circleWaits: '秘社正在等待', chooseSecret: '秘密选择角色',
    seer: (roles, count) => `先知看到：${roles || '无'}（剩余 ${count} 个）`, vp: '胜利点', player: '玩家',
    roles: {
      herbalist: ['🌿','草药师','草药'], miner: ['💎','矿工','水晶'], channeler: ['🔮','通灵师','魔力'], merchant: ['🪙','商人','金币'],
      alchemist: ['⚗️','炼金师','药剂'], seer: ['👁️','先知','窥视'], ritualist: ['🕯️','仪式师','仪式'], thief: ['🗝️','盗贼','偷取']
    },
    rituals: {'verdant-moon':'翠月仪式','glass-star':'琉璃星仪式','root-crown':'根冠仪式','triple-flame':'三焰仪式','silver-well':'银井仪式','thorn-prism':'荆棘棱镜'},
    rules: `<h2>游戏规则</h2><p>每轮开始时，每位玩家从八个角色中秘密选择四个。领手玩家从自己尚未使用的角色中发起一个角色，并选择 <b>恩惠 Favor</b> 获得安全的即时效果，或选择 <b>主张 Claim</b> 争夺更强效果。</p><p>随后按顺时针方向，所有同样选择了该角色的玩家都必须回应。后手选择 Claim 会夺走主行动；本次角色结算结束时，只有最后一位 Claim 玩家获得主张效果。</p><p>共进行五轮。最终结算药剂与仪式的胜利点，并且每 3 枚金币额外获得 1 胜利点。平分时比较草药 + 魔力 + 水晶总数，仍相同则共享胜利。</p><h3>角色</h3><ul><li>🌿 草药师 — 获取草药</li><li>💎 矿工 — 获取水晶</li><li>🔮 通灵师 — 获取魔力</li><li>🪙 商人 — 获取金币</li><li>⚗️ 炼金师 — 调制药剂</li><li>👁️ 先知 — 获取秘密角色信息</li><li>🕯️ 仪式师 — 推进公共仪式</li><li>🗝️ 盗贼 — 获取或偷取金币</li></ul>`
  }
};
let locale = /^zh\b/i.test(navigator.language || '') ? 'zh' : 'en';
const tr = () => I18N[locale];
const roleOrder = Object.keys(I18N.en.roles);
let state = null;
let priv = { round: 0, selected: [], resolved: [], locked: false, intent: null };
let localSelection = new Set();
let lastPhase = '';
let seerPayload = null;
const $ = (id) => document.getElementById(id);
function toast(text) { const t = $('toast'); t.textContent = text; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 1500); }
function me() { return state?.players?.[parti.playerId]; }
function isMyResponse() { return state?.phase === 'responseQueue' && state.responseOrder?.[state.responseIndex] === parti.playerId; }
function roleLabel(id) { return tr().roles[id] || I18N.en.roles[id]; }
function translateMessage(message='') {
  if (locale === 'en') return message;
  if (message === 'Waiting for 3–5 players') return '等待 3–5 位玩家';
  if (message === 'Coven complete') return '秘社仪式已完成';
  if (message === 'Lead player: choose a remaining role') return '领手玩家：请选择一个尚未使用的角色';
  if (message === 'Round reset after host recovery; reselect roles') return '房主恢复后本轮已重置，请重新选择角色';
  let m = message.match(/^Round (\d+): choose 4 roles$/); if (m) return `第 ${m[1]} 轮：请选择 4 个角色`;
  m = message.match(/^Waiting for (.+)$/); if (m) return `等待 ${m[1]}`;
  return message;
}
function roleCard(id) { const info = roleLabel(id); const b = document.createElement('button'); b.className = 'role-card'; b.dataset.role = id; b.innerHTML = `<span class="icon">${info[0]}</span><b>${info[1]}</b><small>${info[2]}</small>`; b.onclick = () => onCard(id); return b; }
function mountHand() { const hand = $('hand'); hand.replaceChildren(...roleOrder.map(roleCard)); }
function onCard(id) { if (!state) return; if (state.phase === 'selectRoles' && !priv.locked) { if (localSelection.has(id)) localSelection.delete(id); else if (localSelection.size < 4) localSelection.add(id); else toast(tr().chooseFour); renderHand(); renderControls(); return; } if (state.phase === 'startRole' && state.leadPlayerId === parti.playerId && priv.selected.includes(id) && !priv.resolved.includes(id)) { localSelection = new Set([id]); renderHand(); renderControls(); } }
function renderPlayers() { const root = $('players'); const ids = state?.seatOrder || []; const existing = new Map(Array.from(root.children).map((el) => [el.dataset.id, el])); for (const id of ids) { let el = existing.get(id); if (!el) { el = document.createElement('div'); el.className = 'seat'; el.dataset.id = id; el.innerHTML = '<div class="avatar"></div><div><div class="seat-name"></div><div class="tokens"></div></div>'; root.appendChild(el); } const p = state.players[id]; el.classList.toggle('me', id === parti.playerId); el.style.opacity = p.connected ? '1' : '.48'; el.querySelector('.avatar').textContent = (p.name || '?').slice(0, 1).toUpperCase(); el.querySelector('.seat-name').textContent = p.name + (id === state.leadPlayerId ? ' ✦' : ''); el.querySelector('.tokens').textContent = `🌿${p.resources.herb} 🔮${p.resources.mana} 💎${p.resources.crystal} 🪙${p.resources.coin} · ${p.vp}${tr().vp}`; existing.delete(id); } for (const el of existing.values()) el.remove(); }
function renderRituals() { const root = $('rituals'); const rituals = state?.rituals || []; root.replaceChildren(...rituals.map((r) => { const d = document.createElement('div'); d.className = 'ritual'; const req = ['herb', 'mana', 'crystal'].filter(k => r.requirements[k]).map(k => `${k === 'herb' ? '🌿' : k === 'mana' ? '🔮' : '💎'} ${r.progress[k] || 0}/${r.requirements[k]}`).join(' · '); d.innerHTML = `<b>🕯️ ${tr().rituals[r.id] || r.name} · ${r.vp}${tr().vp}</b><span>${req}</span>`; return d; })); }
function renderStage() { const stage = $('roleStage'); if (state?.currentRoleId) { const i = roleLabel(state.currentRoleId); stage.innerHTML = `<div><div class="active-card"><span class="icon">${i[0]}</span><b>${i[1]}</b><small>${tr().finalClaim(state.claimHolderId ? state.players[state.claimHolderId]?.name : '')}</small></div><div class="claim-track">${(state.responseOrder || []).map((id, idx) => `<span class="claim-chip">${idx === state.responseIndex ? '➤ ' : ''}${state.players[id]?.name || '?'}</span>`).join('')}</div></div>`; } else { stage.innerHTML = `<div class="active-card" style="opacity:.48"><span class="icon">✦</span><b>${tr().circleWaits}</b><small>${tr().chooseSecret}</small></div>`; } }
function renderHand() { for (const el of Array.from($('hand').children)) { const id = el.dataset.role; const info = roleLabel(id); el.querySelector('b').textContent = info[1]; el.querySelector('small').textContent = info[2]; const selected = state?.phase === 'selectRoles' ? localSelection.has(id) : priv.selected.includes(id); el.classList.toggle('selected', selected); el.classList.toggle('resolved', priv.resolved.includes(id)); el.classList.toggle('locked', priv.locked); const playable = state?.phase === 'selectRoles' || (state?.phase === 'startRole' && state.leadPlayerId === parti.playerId && priv.selected.includes(id) && !priv.resolved.includes(id)); el.disabled = !playable; } }
function intentFor(role, mode) { const p = me(); if (!p) return {}; if (role === 'seer' || role === 'thief') { const target = state.seatOrder.find((id) => id !== parti.playerId && (role !== 'thief' || state.players[id].resources.coin > 0)); return { targetId: target }; } if (role === 'ritualist') { for (const r of state.rituals || []) { const resources = []; for (const k of ['herb', 'mana', 'crystal']) { const need = (r.requirements[k] || 0) - (r.progress[k] || 0); for (let i = 0; i < need && resources.length < (mode === 'claim' ? 2 : 1); i++) if (p.resources[k] > resources.filter((x) => x === k).length) resources.push(k); } if (resources.length) return { ritualId: r.id, resource: resources[0], resources }; } } if (role === 'alchemist') { if (mode === 'claim' && p.resources.herb && p.resources.mana && p.resources.crystal) return { recipeId: 'advanced' }; const avail = ['herb', 'mana', 'crystal'].filter(k => p.resources[k] > 0); if (mode === 'favor' && avail.length >= 2) return { recipeId: `${avail[0]}+${avail[1]}` }; if (mode === 'claim') { const copies = []; for (const k of ['herb', 'mana', 'crystal']) for (let i = 0; i < p.resources[k]; i++) copies.push(k); for (let a = 0; a < copies.length; a++) for (let b = a + 1; b < copies.length; b++) if (copies[a] !== copies[b]) { const used = [a, b]; for (let c = 0; c < copies.length; c++) if (!used.includes(c)) for (let d = c + 1; d < copies.length; d++) if (!used.includes(d) && copies[c] !== copies[d]) return { recipeId: `double:${copies[a]}+${copies[b]}|${copies[c]}+${copies[d]}` }; } } } return {}; }
function submitMode(mode) { const role = state.phase === 'startRole' ? [...localSelection][0] : state.currentRoleId; if (!role) return; const payload = { mode, ...intentFor(role, mode) }; if (state.phase === 'startRole') parti.action('startRole', { roleId: role, ...payload }); else parti.action('respondRole', payload); }
function renderControls() { const c = $('controls'); c.replaceChildren(); if (!state) return; if (state.phase === 'lobby') { const b = document.createElement('button'); b.className = 'action'; b.textContent = me()?.ready ? tr().readyDone : tr().ready; b.disabled = !!me()?.ready; b.onclick = () => parti.ready(); c.appendChild(b); return; } if (state.phase === 'selectRoles') { const b = document.createElement('button'); b.className = 'action'; b.textContent = priv.locked ? tr().locked : tr().lock(localSelection.size); b.disabled = priv.locked || localSelection.size !== 4; b.onclick = () => { parti.action('selectRoles', { roleIds: [...localSelection] }); parti.action('lockRoles'); }; c.appendChild(b); return; } if (state.phase === 'startRole' && state.leadPlayerId === parti.playerId && localSelection.size === 1) { for (const mode of ['favor', 'claim']) { const b = document.createElement('button'); b.className = 'action ' + (mode === 'favor' ? 'secondary' : ''); b.textContent = mode === 'favor' ? tr().takeFavor : tr().makeClaim; b.onclick = () => submitMode(mode); c.appendChild(b); } return; } if (isMyResponse()) { for (const mode of ['favor', 'claim']) { const b = document.createElement('button'); b.className = 'action ' + (mode === 'favor' ? 'secondary' : ''); b.textContent = mode === 'favor' ? tr().takeFavor : tr().challengeClaim; b.onclick = () => submitMode(mode); c.appendChild(b); } return; } if (state.phase === 'gameEnd') { const text = document.createElement('div'); text.textContent = state.winnerIds.includes(parti.playerId) ? tr().shareWin : tr().covenComplete; c.appendChild(text); if (state.seatOrder[0] === parti.playerId) { const b = document.createElement('button'); b.className = 'action'; b.textContent = tr().rematch; b.onclick = () => parti.action('rematch'); c.appendChild(b); } return; } const w = document.createElement('div'); w.textContent = tr().waitingCircle; c.appendChild(w); }
function renderRules() { $('rulesContent').innerHTML = tr().rules; $('rulesBtn').setAttribute('aria-label', locale === 'zh' ? '游戏规则' : 'How to play'); $('langBtn').textContent = tr().langButton; $('langBtn').setAttribute('aria-label', tr().langLabel); document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en'; }
function seerText() { if (!seerPayload) return ''; const roles = (seerPayload.roles || []).map(id => roleLabel(id)[1]).join(locale === 'zh' ? '、' : ', '); return tr().seer(roles, seerPayload.count); }
function patch() { if (!state) return; $('phaseLabel').textContent = state.phase === 'lobby' ? tr().gathering : translateMessage(state.message || state.phase); $('roundBadge').textContent = tr().round(state.round); const st = seerText(); $('message').textContent = translateMessage(state.message) + (st ? ` · ${st}` : ''); $('privateHint').textContent = priv.locked ? tr().hiddenLocked(priv.resolved.length) : tr().hiddenSelection(localSelection.size); renderPlayers(); renderRituals(); renderStage(); renderHand(); renderControls(); renderRules(); }
mountHand(); renderRules();
parti.onState((s) => { state = s; if (lastPhase !== s.phase) { lastPhase = s.phase; if (s.phase === 'selectRoles' && priv.round !== s.round) localSelection.clear(); if (s.phase === 'startRole') localSelection.clear(); } patch(); });
parti.onEvent('game:private-state', (p) => { priv = p; if (state?.phase === 'selectRoles' && p.selected.length && !p.locked) localSelection = new Set(p.selected); patch(); });
parti.onEvent('game:seer', (p) => { seerPayload = p; toast(seerText()); patch(); });
$('rulesBtn').onclick = () => $('rulesDialog').showModal();
$('closeRules').onclick = () => $('rulesDialog').close();
$('langBtn').onclick = () => { locale = locale === 'zh' ? 'en' : 'zh'; mountHand(); patch(); };
parti.exposeToAgent?.((s) => ({ summary: locale === 'zh' ? 'Grand Coven：秘密选择4个角色。Favor安全，Claim更强但可能被之后同角色玩家夺走。' : 'Grand Coven: secretly choose 4 roles. Favor is safe; Claim is stronger but can be stolen by later matching players.', phase: s.phase, round: s.round, you: parti.playerId, leadPlayerId: s.leadPlayerId, currentRoleId: s.currentRoleId, publicPlayers: s.players, rituals: s.rituals, privateRoles: priv.selected, privateResolved: priv.resolved, availableActions: s.phase === 'selectRoles' ? ['selectRoles', 'lockRoles'] : s.phase === 'startRole' && s.leadPlayerId === parti.playerId ? ['startRole'] : isMyResponse() ? ['respondRole'] : s.phase === 'gameEnd' ? ['rematch'] : [] }));
parti.ready();
